version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/zsem.smuggr.xyz.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/www/certbot:/var/www/certbot
    ports:
      - "${HOST_PORT:-80}:80"
      - "${HOST_PORT_SSL:-443}:443"
    environment:
      - SERVER_NAME=${DOMAIN}
    depends_on:
      - goptivum
    networks:
      - app-network

  goptivum:
    image: smeggmann99/goptivum:${VERSION}
    container_name: goptivum
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - API_PORT=${API_PORT:-3001}
      - DIST_PATH=/app/dist
    ports:
      - "${API_HOST_PORT:-3001}:${API_PORT:-3001}"
    networks:
      - app-network
    volumes:
      - ./build/Goptivum/.env:/app/.env
      - goptivum_db:/app/db

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - ./certbot/www/certbot:/var/www/certbot
    command: >
      certonly
      --webroot
      --webroot-path=/var/www/certbot
      --agree-tos
      --email ${CERTBOT_EMAIL:-default@example.com}
      --no-eff-email
      -d ${DOMAIN}

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/www/certbot:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --deploy-hook 'nginx -s reload'; sleep 12h; done"

networks:
  app-network:

volumes:
  certbot_etc:
  certbot_var:
  goptivum_db: